name: GitHub to Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]

jobs:
  discord_notification:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "@here",
            "embeds": [{
              "title": "🚀 **GitHub Notification**",
              "description": "**Repository**: [${{ github.repository }}](${{ github.event.repository.html_url }})\n**Event**: ${{ github.event_name }}\n**User**: ${{ github.actor }}\n**Branch**: ${{ github.ref_name || 'N/A' }}\n**Commit Message**: ${{ github.event.head_commit.message || 'N/A' }}\n🔗 [Voir sur GitHub](${{ github.event.head_commit.url || github.event.pull_request.html_url || github.event.repository.html_url }})"
            }]
          }' $DISCORD_WEBHOOK