name: Mirror webappreact
on:
    pull_request:
        branches:
            - main
        paths:
            - 'webappreact/**'
    push:
        branches:
            - main
        paths:
            - 'webappreact/**'

jobs:
  push_to_prod:
    name: Push repository to prod webappreact
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push only main branch to target repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL_WEB }}
          ssh_private_key: ${{ secrets.CLONE_KEY }}
          target_branch: main  # 🔥 Push only to main
          mirror_mode: false   # ⛔ Prevents deleting other branches

    